language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install pycodestyle
# command to run tests
script:
  - pycodestyle HujiBot/*.py
  - pycodestyle Rezabot/*.py
  - pycodestyle webcite.py
  - pycodestyle categorize.py
